site_name: docs.mintthemoon.xyz
nav:
- Kujira Resources: kujira-resources.md
- Kujira Node Guide: kujira-node-guide.md
- Kujira Statesync: kujira-statesync.md
theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
    primary: light green
    accent: deep orange
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: light green
    accent: deep orange
  font:
    text: Noto Sans
    code: Noto Sans Mono
  icon:
    logo: material/book
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences