site_name: mintwiki
nav:
- Kujira:
  - Resources: kujira/resources.md
  - Statesync: kujira/statesync.md
  - Node Guide: kujira/node-guide.md
  - Validator Guide: kujira/validator-guide.md
  - Oracle Guide: kujira/oracle-guide.md
- Bitcanna:
  - Resources: bitcanna/resources.md
  - Statesync: bitcanna/statesync.md
  - Node Guide: bitcanna/node-guide.md
  - Validator Guide: bitcanna/validator-guide.md
theme:
  name: material
  font:
    text: Noto Sans
    code: Noto Sans Mono
  icon:
    logo: material/book
  palette:
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: light green
    accent: deep orange
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
    primary: light green
    accent: deep orange
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true